# Assignment 5: Reinforcement learning and Classification
*Group 11: Alexandra Parkegren & Albin Sjöstrand*

*Hours spent Alexandra: *

*Hours spent Albin: *


# Primer

## Decision Making
The problem of **decision making under uncertainty** (commonly known as **reinforcement learning**) can be broken down into
two parts. First, how do we learn about the world? This involves both the
problem of modeling our initial uncertainty about the world, and that of drawing conclusions from evidence and our initial belief. Secondly, given what we
currently know about the world, how should we decide what to do, taking into
account future events and observations that may change our conclusions?
Typically, this will involve creating long-term plans covering possible future
eventualities. That is, when planning under uncertainty, we also need to take
into account what possible future knowledge could be generated when implementing our plans. Intuitively, executing plans which involve trying out new
things should give more information, but it is hard to tell whether this information will be beneficial. The choice between doing something which is already
known to produce good results and experiment with something new is known
as the **exploration-exploitation dilemma**.

## The exploration-exploitation trade-off

Consider the problem of selecting a restaurant to go to during a vacation. Lets say the
best restaurant you have found so far was **Les Epinards**. The food there is
usually to your taste and satisfactory. However, a well-known recommendations
website suggests that **King’s Arm** is really good! It is tempting to try it out. But
there is a risk involved. It may turn out to be much worse than **Les Epinards**,
in which case you will regret going there. On the other hand, it could also be
much better. What should you do?
It all depends on how much information you have about either restaurant,
and how many more days you’ll stay in town. If this is your last day, then it’s
probably a better idea to go to **Les Epinards**, unless you are expecting **King’s
Arm** to be significantly better. However, if you are going to stay there longer,
trying out **King’s Arm** is a good bet. If you are lucky, you will be getting much
better food for the remaining time, while otherwise you will have missed only
one good meal out of many, making the potential risk quite small.

## Overview
* To make things concrete, we will first focus on decision making under **no** uncertainity, i.e, given we have a world model, we can calculate the exact and optimal actions to take in it. We will first introduce **Markov Decision Process (MDP)** as the world model. Then we give one algorithm (out of many) to solve it.


* Next, we will work through one type of reinforcement learning algorithm called Q-learning. Q-learning is an algorithm for making decisions under uncertainity, where uncertainity is over the possible world model (here MDP). It will find the optimal policy for the **unknown** MDP, assuming we do infinite exploration.

## Markov Decision Process

Markov Decision Process (MDP) provides a mathematical framework for modeling sequential decision making under uncertainty. A MDP consists of five parts: the specific decision times, the state space of the environment/system, the available actions for the decision maker, the rewards, and the transition probabilities between the states.

* Decision epochs: $t={1,2,...,T}$, where $T\leq \infty$
* State space: $S=\{s_1,s_2,...,s_N\}$ of the underlying environment
* Action space $A=\{a_1,a_2,...,a_K\}$ available to the decision maker at each decision epoch
* Reward functions $R_t = r(a_t,s_t,s_{t+1})$ for the current state and action, and the resulting next state
* Transition probabilities $p(s'|s,a)$ that taking action $a$ in state $s$ will lead to state $s'$

At a given decision epoch $t$ and system state $s_t$, the decions maker, or *agent*, chooses an action $a_t$, the system jumps to a new state $s_{t+1}$ according to the transition probability $p(s_{t+1}|s_t,a_t)$, and the agent receives a reward $r_t(s_t,a_t,s_{t+1})$. This process is then repeated for a finite or infinite number of times.

A *decision policy* is a function $\pi: s \rightarrow a$, that gives instructions on what action to choose in each state. A policy can either be *deterministic*, meaning that the action is given for each state, or *randomized* meaning that there is a probability distribution over the set of possible actions. Given a specific policy $\pi$ we can then compute the the *expected total reward* when starting in a given state $s_1 \in S$, which is also known as the *value* for that state, 

$$V^\pi (s_1) = E\left[ \sum_{t=1}^{T} r(s_t,a_t,s_{t+1}) {\Large |} s_1\right] = \sum_{t=1}^{T} r(s_t,a_t,s_{t+1}) p(s_{t+1} | a_t,s_t)$$ 

where $a_t = \pi(s_t)$. To ensure convergence and to control how much credit to give to future rewards, it is common to introduce a *discount factor* $\gamma \in [0,1]$. For instance, if you think all future rewards should count equally, you would use $\gamma = 1$, while if you only care less about future rewards you would use $\gamma < 1$. The expected total *discounted* reward becomes

$$V^\pi( s_1) = \sum_{t=1}^T \gamma^{t-1} r(s_t,a_t, s_{t+1}) p(s_{t+1} | s_t, a_t) $$

Now, to find the *optimal* policy we want to find the policy $\pi^*$ that gives the highest total reward $V^{\pi^*}(s)$ for all $s\in S$. That is

$$V^{\pi^*}(s) \geq V^\pi(s), s\in S$$

The problem of finding the optimal policy is a _dynamic programming problem_. It turns out that a solution to the optimal policy problem in this context is the *Bellman equation*. The Bellman equation is given by

$$V(s) = \max_{a\in A} \left\{\sum_{s'\in S} p(s'|s,a)( r(s,a,s') +\gamma V(s')) \right\}$$

Thus, it can be shown that if $\pi$ is a policy such that $V^\pi$ fulfills the Bellman equation, then $\pi$ is an optimal policy.

A real world example would be an inventory control system. Your states would be the amount of items you have in stock. Your actions would be the amount to order. The discrete time would be the days of the month. The reward would be the profit.  

A major drawback of MDPs is called the "Curse of Dimensionality". MDPs unfortunately do not scale very well with increasing sets of states or actions.   


## Question 1

In this first question we work with the deterministic MDP, no code is necessary in this part.

Setup:

* The agent starts in state **S**
* The actions possible are **N** (north), **S** (south), **E** (east), and **W** west. 
* Note, that you cannot move outside the grid, thus all actions are not available in every box.
* When reaching **F**, the game ends (absorbing state).
* The numbers in the boxes represent the rewards you receive when moving into that box. 
* Assume no discount in this model: $\gamma = 1$

The reward of a state $r(s=(x, y))$ is given by the values on the grid:
    
| a| b |c |
|-- |--|--|
|-1    | 1|**F**|
|0     |-1|     1|  
|-1    | 0|    -1|  
|**S**|-1|     1|

Let $(x,y)$ denote the position in the grid, such that $S=(0,0)$ and $F=(2,3)$.



**1a) What is the optimal path of the MDP above? Is it unique? Submit the path as a single string of directions. E.g. NESW will make a circle.**

Best path: `EENNN`

Alternative path: `EENNWNE`

It's unique in that it's the one path that doesn't have an negative sum, but instead 0, while also being the shortest. There is an alternative path
that has the same sum of 0, but takes on two additional moves in order to reach F.



**1b) What is the optimal policy (i.e. the optimal action in each state)?**

Position has the optimal action(-s) with the coherent reward points

(0,0):  E  ||  N  = -1

(0,1):  E = 1

(0,2):  W  ||  N  = -1

(1,0):  E  ||  N   = 0 (if we are allowed to return to start S is also a equally possible policy)

(1,1):  E  ||  W  ||  N  ||  S  =-1

(1,2):  N  ||  S = 1 

(2,0):  E  ||  N  ||  S =-1

(2,1):  E  ||  N   = 1

(2,2):  N = 0

(3,0):  E = 1

(3,1):  E = 0

(3,2): absorbing state have no possible actions



## Value Iteration

**1c) What is expected total reward for the policy in 1b)?**

V(s) is the value you expect to obtain when you follow the current policy starting from state s

From this given specific policy $\pi$ we can compute the expected total reward by adding 
the rewards. The value is the current reward (from the position we are standing at) 
plus the optimal actions reward, the value expected to obtain.
The new value from an action will be = (currentStateReward + 1 \* nextStateReward) 
where gamma=1 (it'll care more about rewards earned immediately).
These values will be added up/summed at the end into V(s), which will represent the expected 
total reward when following the current policy sdtarting from state s.

We start at (0,0) and follow the optimal policy (see 1b). 
Some states have multiple path choices. 
We follow all alternative paths until we reach the goal and then we'll be able 
to compare the sum value to decide which way is the most optimal.
Some path cross their own way, we then ignore these since the total sum will not improve by this.

The expencted total reward for the best chosen path is: `0`. 

The calculation for this was as follows

(0,0): Action E, value = 0 - 1=-1

(0,1): Action E, value = -1+ 1= 0

(0,2): Action N, value = 1 - 1= 0

(1,2): Action N, value = -1+ 1= 0

(2,2): Action N, value = 1 + 0= 1

(3,2) sumValue = 0



Here are the other possible paths but with worse value:

(0,0):N, (1,0):E, (1,1):E, (1,2):N, (2,2):N, (3,2) sumV=-1-1-1+0+1= -2

(0,0):N, (1,0):E, (1,1):N, (2,1):E, (2,2):N, (3,2) sumV=-1-1-1+0+1= -2

(0,0):N, (1,0):E, (1,1):N, (2,1):N, (3,1):E, (3,2) sumV=-1-1-1+0+1= -2

(0,0):N, (1,0):N, (2,0):E, (2,1):E, (2,2):N, (3,2) sumV=-1-1-1+0+1= -2

(0,0):N, (1,0):N, (2,0):E, (2,1):N, (3,1):E, (3,2) sumV=-1-1-1+0+1= -2

(0,0):N, (1,0):N, (2,0):N, (3,0):E, (3,1):E, (3,2) sumV=-1-1-1+0+1= -2


## Question 2

For larger problems we need to utilize algorithms to determine the optimal policy $\pi^*$. *Value iteration* is one such algorithm that iteratively computes the value for each state. Recall that for a policy to be optimal, it must satisfy the Bellman equation above, meaning that plugging in a given candidate $V^*$ in the right-hand side (RHS) of the Bellman equation should result in the same $V^*$ on the left-hand side (LHS). This property will form the basis of our algorithm. Essentially, it can be shown that repeated application of the RHS to any intial value function $V^0(s)$ will eventually lead to the value $V$ which statifies the Bellman equation. Hence repeated application of the Bellman equation will also lead to the optimal value function. We can then extract the optimal policy by simply noting what actions that satisfy the equation. The process of repeated application of the Bellman equation what we here call the _value iteration_ algorithm.

The value iteration algorithm practically procedes as follows:

```
epsilon is a small value, threshold
for x from i to infinity 
do
    for each state s
    do
        V_k[s] = max_a Σ_s' p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′])
    end
    if  |V_k[s]-V_k-1[s]| < epsilon for all s
        for each state s,
        do
            π(s)=argmax_a ∑_s′ p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′])
            return π, V_k 
        end
end

```






**Example:** We will illustrate the value iteration algorithm by going through two iterations. Below is a 3x3 grid with the rewards given in each state. Assume now that given a certain state $s$ and action $a$, there is a probability of 0.8 that that action will be performed and a probability of 0.2 that no action is taken. For instance, if we take action **E** in state $(x,y)$ we will go to $(x+1,y)$ 80 percent of the time (given that that action is available in that state, that is, we stay on the grid), and remain still 20 percent of the time. We will use have a discount factor $\gamma = 0.9$. Let the initial value be $V^0(s)=0$ for all states $s\in S$. 

| | | |  
|----------|----------|---------|  
|0|0|0|
|0|10|0|  
|0|0|0|  


teacher said:
(0,1)
Action **N**: 0.8(10) + 0.2(0) = 8
(0,1)
Action **N**: 0.8(0) + 0.2(10) = 2

**Iteration 1**: The first iteration is trivial, $V^1(s)$ becomes the $\max_a \sum_{s'} p(s'|s,a) r(s,a,s')$ since $V^0$ was zero for all $s'$. The updated values for each state become

| | | |  
|----------|----------|---------|  
|0|8|0|
|8|2|8|  
|0|8|0|  

**Iteration 2**:  
  
Staring with cell (0,0) (lower left corner): We find the expected value of each move:  
Action **S**: 0  
Action **E**: 0.8( 0 + 0.9 \* 8) + 0.2(0 + 0.9 \* 0) = 5.76  
Action **N**: 0.8( 0 + 0.9 \* 8) + 0.2(0 + 0.9 \* 0) = 5.76  
Action **W**: 0

Hence any action between **E** and **N** would be best at this stage.

Similarly for cell (1,0):

Action **N**: 0.8( 10 + 0.9 \* 2) + 0.2(0 + 0.9 \* 8) = 10.88 
(Action **N** is the maximizing action)  




Similar calculations for remaining cells give us:

| | | |  
|----------|----------|---------|  
|5.76|10.88|5.76|
|10.88|8.12|10.88|  
|5.76|10.88|5.76|  




**2a)** Implement the value iteration algorithm just described here in python, 
and show the converging optimal value function and the optimal policy for the above 
3x3 grid. Hint: use the pseudo-code above as a starting point, but be sure to explain 
what every line does.

"show the converging optimal value function"

$$V^\pi( s_1) = \sum_{t=1}^T \gamma^{t-1} r(s_t,a_t, s_{t+1}) p(s_{t+1} | s_t, a_t) $$



"show the optimal policy (that fulfills the bellman equation)"

$$V(s) = \max_{a\in A} \left\{\sum_{s'\in S} p(s'|s,a)( r(s,a,s') +\gamma V(s')) \right\}$$


In [133]:
import numpy as np

def getPossibleActions(env,currentState):

    #four acitions/ moves of the agent: LEFT = 0, DOWN = 1, RIGHT = 2, UP = 3
    possibleActions = []

    #corresponding Action will give the neighbour with the corresponging rate
    possibleSuccessorStates = []
    possibleSuccessorReward = []

    posX = currentState[0]
    posY = currentState[1]

    envXLength = env.shape[0]
    envYLenght = env.shape[1]
    
    #if it can move to the left
    if (posY-1) >= 0:
        possibleActions.append(0)
        possibleSuccessorStates.append([posX,posY-1])
        possibleSuccessorReward.append(env[posX,posY-1])

    #if the agent can move down
    if (posX+1) <= (envXLength-1):
        possibleActions.append(1)
        possibleSuccessorStates.append([posX+1,posY])
        possibleSuccessorReward.append(env[posX+1,posY])

    #if the agent can move to the right
    if (posY+1) <= (envYLenght-1):
        possibleActions.append(2)
        possibleSuccessorStates.append([posX,posY+1])
        possibleSuccessorReward.append(env[posX,posY+1])

    #if the agent can move up
    if (posX-1) >= 0:
        possibleActions.append(3)
        possibleSuccessorStates.append([posX-1,posY])
        possibleSuccessorReward.append(env[posX-1,posY])

    return possibleActions, possibleSuccessorStates, possibleSuccessorReward



# gamma ex = 0.9 will care more about rewards earned immediately rather than later.
# there is a probability of probMove(ex 0.8) that that action will be performed and probStay (ex 0.2) that no action is taken
def getOptimalValue(env,currentState,probMove, probStay,gamma,eps,initalEnviroment):

    currentReward = env[currentState]
    possActions, possSuccStates, possSuccStatesRewards = getPossibleActions(env,currentState)

    bestValue = 0;
    
    for i in range(0,len(possActions)):
        if initalEnviroment:
            #this is the way to count the value for the initial enviroment
            newValue = probMove*(possSuccStatesRewards[i]) + probStay*(currentReward)
        else:
            #the optional policy V_k[s] = max_a Σ_s' p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′])
            newValue = probMove*(currentReward + gamma*possSuccStatesRewards[i]) + probStay*(currentReward + gamma*currentReward)

        #the converging optimal value function π(s)=argmax_a ∑_s′ p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′]))
        #initialize for first loop or, if the newValues is better (within a epsilon range)
        if (i == 0) or ((newValue > bestValue)): # and ((newValue - bestValue) < eps)):
            bestValue = newValue   
        
    return bestValue
    


def updateEnviroment(env,probMove,probStay,gamma,eps,n_wanted_updates,initalEnvIncluded):

    #save the inital enviroment and all updated enviroments for return later
    listOfEnviroments = [env]
    
    # one loop will create a new enviroment with values from the first
    for i in range (0,n_wanted_updates): 
        
        oldEnv = listOfEnviroments[i]
        newEnviroment = np.zeros(env.shape)
        
        for x in range(0,env.shape[1]):
            for y in range(0,env.shape[0]):
                pos = (x,y)
                
                if initalEnvIncluded & (i==0):
                    bValue = getOptimalValue(oldEnv,pos,probMove,probStay,gamma,eps,True)
                else:
                    bValue = getOptimalValue(oldEnv,pos,probMove,probStay,gamma,eps,False)
                #make a enviroment with the best values
                newEnviroment[pos] = bValue
            
        #save a new updated enviroment into an array to save the history
        listOfEnviroments.append(newEnviroment)
        
    return listOfEnviroments




#currentState = (0,0)
#enviroment = np.array([[0,8,0],[8,2,8],[0,8,0]])
#possibleActions, possibleSuccessorStates, possibleSuccessorReward = getPossibleActions(enviroment,currentState)
#bestValue= getOptimalValue(enviroment,currentState,0.8,0.2,0.9,0.5)



n_wanted_updates = 2
enviroment = np.array([[0,0,0],[0,10,0],[0,0,0]])
enviroments = updateEnviroment(enviroment,0.8,0.2,0.9,0.5,n_wanted_updates,True)

for i in range(0,len(enviroments)):
    if i==0:
        print('the initial enviroment: ')
    else:
        print('an updates enviroment: ')
    print(enviroments[i])



print()
n_wanted_updates = 30
enviroment2 = np.array([[0,0,0],[0,10,0],[0,0,0]])
enviroments2 = updateEnviroment(enviroment2,0.8,0.2,0.9,0.5,n_wanted_updates,True)
print('result of one enviroment updated %d number of times :' %(n_wanted_updates))
print(enviroments2[n_wanted_updates])
enviroment3 = np.array([[0,0,10],[0,0,0],[0,0,0]])
enviroments3 = updateEnviroment(enviroment3,0.8,0.2,0.9,0.5,n_wanted_updates,True)
print('result of another enviroment updated %d number of times :' %(n_wanted_updates))
print(enviroments3[n_wanted_updates])



the initial enviroment: 
[[ 0  0  0]
 [ 0 10  0]
 [ 0  0  0]]
an updates enviroment: 
[[0. 8. 0.]
 [8. 2. 8.]
 [0. 8. 0.]]
an updates enviroment: 
[[ 5.76 10.88  5.76]
 [10.88  8.12 10.88]
 [ 5.76 10.88  5.76]]

result of one enviroment updated 30 number of times :
[[6.06490857e+08 6.06491100e+08 6.06490857e+08]
 [6.06491100e+08 6.06491100e+08 6.06491100e+08]
 [6.06490857e+08 6.06491100e+08 6.06490857e+08]]
result of another enviroment updated 30 number of times :
[[6.06490857e+08 6.06491100e+08 6.06491100e+08]
 [6.06485828e+08 6.06490857e+08 6.06491100e+08]
 [6.06436926e+08 6.06485828e+08 6.06490857e+08]]


**2b)** Explain why the result of 2a) does not depend on the initial value $V_0$.

The calculatons are divided into sequence of smaller subproblems:
Every different state will be considered separately.
The possible actions for different states are independent of each other.


For the first loop the initial value will be spread out into the matrix. 
The first iteration is trivial since by then we've moved away from the initial value.
And when for example not care how the enviroment was initialized (see the last two prints above)

## Reinforcement Learning (RL)
Until now, we understood that knowing the MDP, specifically $p(s'|a,s)$ and $r(a,s,s')$ allows us to efficiently find the optimal policy using the value iteration algorithm. Reinforcement learning (RL) or decision making under uncertainity, however, arises from the question of making optimal decisions without knowing the true world model (the MDP in this case).

So far we have defined the value function for a policy through $V^\pi$. Let's now define the *action-value function*

$$Q^\pi(s,a) = \sum_{s'} p(s'|a,s) [r(a,s,s') + \gamma V^\pi(s')]$$

The value function and the action-value function are directly related through

$$V^\pi (s) = \max_a Q^\pi (s,a)$$

i.e, the value of taking action $a$ in state $s$ and then following the policy $\pi$ onwards. Similarly to the value function, the optimal $Q$-value equation is:

$$Q^*(s,a) = \sum_{s'} p(s'|a,s) [r(a,s
]\,s') + \gamma V^*(s')]$$

and the relationship between $Q^*(s,a)$ and $V^*(s)$ is simply

$$V^*(s) = \max_{a\in A} Q^*(s,a).$$

## Q-learning

Q-learning is a RL-method where the agent learns about its unknown environment (i.e. the MDP is unknown) through exploration. In each time step *t* the agent chooses an action *a* based on the current state *s*, observes the reward *r* and the next state *s'*, and repeats the process in the new state. Q-learning is then a method that allows the agent to act optimally. Here we will focus on the simplest form of Q-learning algorithms, which can be applied when all states are known to the agent, and the state and action spaces are reasonably small. This simple algorithm uses a table of Q-values for each $(s,a)$ pair, which is then updated in each time step using the update rule in step $k+1$

$$Q_{k+1}(s,a) = Q_k(s,a) + \alpha \left( r(s,a) + \gamma \max \{Q_k(s',a')\} - Q_k(s,a) \right) $$ 

where $\gamma$ is the discount factor as before, and $\alpha$ is a pre-set learning rate. It can be shown that this algorithm converges to the optimal policy of the underlying MDP for certain values of $\alpha$ as long as there is sufficient exploration. While a constant $\alpha$ generally does not guarantee us to reach true convergence, we keep it constant at $\alpha=0.1$ for this assignment.

## OpenAI Gym

We shall use already available simulators for different environments (worlds) using the popular OpenAI Gym library. It just implements [different types of simulators](https://gym.openai.com/) including ATARI games. Although here we will only focus on simple ones, such as the [Chain enviroment](https://gym.openai.com/envs/NChain-v0/) illustrated below.
![alt text](https://chalmersuniversity.box.com/shared/static/6tthbzhpofq9gzlowhr3w8if0xvyxb2b.jpg)
The figure corresponds to an MDP with 5 states $S = \{1,2,3,4,5\}$ and two possible actions $A=\{a,b\}$ in each state. The arrows indicate the resulting transitions for each state-action pair, and the numbers correspond to the rewards for each transition.




## Question 3
You are to first familiarize with the framework using its [documentation](http://gym.openai.com/docs/), and then implement the Q-learning algorithm for the Chain enviroment (called 'NChain-v0') using default parameters. Finally print the $Q^*$ table at convergence. Convergence is **not** a constant value, rather a stable plateau with some noise. Take $\gamma=0.95$. You can refer to the Q-learning (frozen lake) Jupyter notebook shown in class, uploaded on Canvas. Hint: start with a small learning rate.


In [141]:
# For testing where convergence on chain
val5a = 0
val1b = 0

for n in range(0, 200):
    val5a = val5a + 10 * 0.95**n
    val1b = val1b + 2 * 0.95**n
#    print('current val 5a %f, current val 1b %f ' %(val5a,val1b))

#print('Total val 5a %f, current val 1b %f ' %(val5a,val1b))

val = 0
for n in range(0, 200):
    val = val + 10 * 0.95**n
    #print('current val: ', val)

#print('Total val:', val)

In [162]:
import gym
import random

num_episodes = 1000
gamma = 0.9
learning_rate = 0.8
epsilon = 1

env = gym.make('NChain-v0')
env.reset()

# initialize the Q table
Q = np.zeros((env.observation_space.n, env.action_space.n))
exp_exp_tradeoff = random.uniform(0,1)

for _ in range(num_episodes):
	state = env.reset()
	done = False
	while done == False:
        # First we select an action:
		if random.uniform(0, 1) < epsilon: # Flip a skewed coin
			action = env.action_space.sample() # Explore action space
		else:
			action = np.argmax(Q[state,:]) # Exploit learned values
        # Then we perform the action and receive the feedback from the environment
		new_state, reward, done, info = env.step(action)
        # Finally we learn from the experience by updating the Q-value of the selected action
		update = reward + (gamma*np.max(Q[new_state,:])) - Q[state, action]
		Q[state,action] += learning_rate*update 
		state = new_state

print('Q-table: ')
print(Q)

Q-table: 
[[18.49086294 19.67473114]
 [22.11221996 19.76885434]
 [25.01656377 18.90197004]
 [20.80278135 27.90070762]
 [37.72279119 22.7879921 ]]


In [164]:
import gym
import random
import numpy as np

# init parameters for this scenario
learning_rate = 0.8
discount_factor = 0.9
epsilon = 1 # exploration rate
min_epsilon = 0.1 # minimum exploration rate
max_epsilon = 1 # maximum exploration rate
decay = 0.01 #e-greedy -> minize the exploration rate for each episode
train_episodes = 1000
max_steps = 10

# init environment
env = gym.make('NChain-v0')
env.reset()

# init Q table
Q = np.zeros((env.observation_space.n, env.action_space.n))

# store results
training_rewards = []
epsilons = []

# train the algorithm with specified no of training episodes
for episode in range(train_episodes):
    state = env.reset()
    total_training_rewards = 0
    done = False

    #for step in range(max_steps):
    while done == False:

        # First we select an action:
        # exploit (aldready something we know) or explore (new)
        exp_exp_tradeoff = random.uniform(0,1)        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(Q[state,:])     # Exploit learned values
        else:
            action = env.action_space.sample() # Random explore action space

        # action is taken new state, reward and criteria for stopping is observed
        new_state, reward, done, info = env.step(action)

        # update Q table with current state, learning rate, reward, discount, action taken and if the enivorment is done
        update = reward + (discount_factor * np.max(Q[new_state, :])) - Q[state, action]
        Q[state, action] += update * learning_rate

        #Q[state, action] = Q[state, action] + learning_rate * (reward + discount_factor * np.max(Q[new_state, :])) - Q[state, action]

        total_training_rewards += reward
        state = new_state

        # check is environment is done
        #if done == True:
            #print("Total reward for episode {}: {}".format(episode, total_training_rewards))
            #break
    
    # epsilon is updated for the exploitation exploration trade-off, e-greedy algorithm
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay * episode)
    training_rewards.append(total_training_rewards) # total rewards
    epsilons.append(epsilon) # save epsilon values

print('Q-table:')
print(Q)

Q-table:
[[10.52299248 17.69315329]
 [10.22354802 12.09274992]
 [17.8139887  11.22472349]
 [19.34880604 13.42212144]
 [18.94470438 13.51436317]]


## Question 4

**4a) Define the MDP corresponding to the Chain environment above and verify that the optimal $Q^*$ value obtained using simple Q-learning is the same as the optimal value function $V^*$ for the corresponding MDP's optimal action. Hint: compare values obtained using value iteration and Q-learning.**

Traversing chain. Big reward at the end.

In [166]:
import numpy as np



def createEnviroment():
    # for corresponding state the action will give [succState, succReward]
    #states = np.array([[1],[2],[3],[4],[5]])
    successorStatesWithReward = {'a':[2,0],'b':[1,2]},{'a':[3,0],'b':[1,2]},{'a':[4,0],'b':[1,2]},{'a':[5,0],'b':[1,2]},{'a':[5,10],'b':[1,2]}
    enviroment = np.zeros((5,2))
    return enviroment, successorStatesWithReward



def getSuccRewardFromAction(succStatesRewards, currentState, action):
    actionStateRew = succStatesRewards[currentState]
    succStateWithReward = actionStateRew[action]
    #print('the state %d has the possible actions %s and will make the action %s' %(currentState,actionStateRew,action))
    #succState  = succStateWithReward[0]
    succReward = succStateWithReward[1]
    return succReward


def getOptimalValue11(succStatesRewards,currentState):
    bestSuccReward = 0
    currentStatesPossActions = succStatesRewards[currentState]
    succstateA,succRewardA = currentStatesPossActions['a']
    succstateB,succRewardB = currentStatesPossActions['b']
    if succRewardA > succRewardB:
        bestSuccReward = succRewardA
    else:
        bestSuccReward = succRewardB       
    return bestSuccReward
    



def updateEnviroment(env,succStatesRewards,gamma,learning_rate,n_wanted_updates):
    #save the inital enviroment and all updated enviroments for return later
    listOfEnviroments = [env]
    possibleActions = ['a','b']
    # one loop will create a new enviroment with values from the first
    for i in range (0,n_wanted_updates): 
        oldEnviroment = listOfEnviroments[i]
        newEnviroment = np.zeros(env.shape)
        for state in range(0,5):
            for a in range(0,2):
                action = possibleActions[a]
                succReward = getSuccRewardFromAction(succStatesRewards, state, action)
                bestSuccReward = getOptimalValue11(succStatesRewards,state)
                currentReward = oldEnviroment[state,a]
                # Q-learning formula
                newValue = currentReward + (learning_rate*(succReward + (gamma*bestSuccReward) - currentReward))
                #update with new reward
                newEnviroment[state,a] = newValue
        #save a new updated enviroment into an array to save the history
        listOfEnviroments.append(newEnviroment)     
    return listOfEnviroments



gamma = 0.5  #"discount_factor"
n_wanted_updates = 4
learning_rate = 0.8

env, succStatesRewards = createEnviroment()
#print('state %d can take action to get to states with rewards %s: ' %(env[0],succStatesRewards[0]))
#print('first state take action a and go to state %d, to get reward %d' %(succStatesRewards[0]['a'][0],succStatesRewards[0]['a'][1]))

listOfEnv = updateEnviroment(env,succStatesRewards,gamma,learning_rate,n_wanted_updates)

for i in range(0,len(listOfEnv)):
    print(listOfEnv[i])

########


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0.8  2.4]
 [ 0.8  2.4]
 [ 0.8  2.4]
 [ 0.8  2.4]
 [12.   5.6]]
[[ 0.96  2.88]
 [ 0.96  2.88]
 [ 0.96  2.88]
 [ 0.96  2.88]
 [14.4   6.72]]
[[ 0.992  2.976]
 [ 0.992  2.976]
 [ 0.992  2.976]
 [ 0.992  2.976]
 [14.88   6.944]]
[[ 0.9984  2.9952]
 [ 0.9984  2.9952]
 [ 0.9984  2.9952]
 [ 0.9984  2.9952]
 [14.976   6.9888]]


In [206]:

def createEnviroment():
    # for corresponding state the action will give [succState, succReward]
    #states = np.array([[1],[2],[3],[4],[5]])
    successorStatesWithReward = {'a':[2,0],'b':[1,2]},{'a':[3,0],'b':[1,2]},{'a':[4,0],'b':[1,2]},{'a':[5,0],'b':[1,2]},{'a':[5,10],'b':[1,2]}
    enviroment = np.zeros((5,2))
    return enviroment, successorStatesWithReward

def getSuccRewardFromAction(succStatesRewards, currentState, action):
    actionStateRew = succStatesRewards[currentState]
    succStateWithReward = actionStateRew[action]
    #print('the state %d has the possible actions %s and will make the action %s' %(currentState,actionStateRew,action))
    #succState  = succStateWithReward[0]
    succReward = succStateWithReward[1]
    return succReward

def getAllSuccRewardForState(succStatesRewards, currentState):
    possabilitiesForState = succStatesRewards[currentState]
    possRewards = [0,0]
    possActions = ['a','b']
    for i in range(0,2):
        action = possActions[i]
        stateAndReward = possabilitiesForState[action]
        possRewards[i] = stateAndReward[1] 
    return possRewards
    


# gamma ex = 0.9 will care more about rewards earned immediately rather than later.
# there is a probability of probMove(ex 0.8) that that action will be performed and probStay (ex 0.2) that no action is taken
def getOptimalValue(env,succStatesRewards,pos,probMove,probStay,gamma,eps,initalEnviroment):
    
    action = possibleActions[pos[1]]
    state = pos[0]
    print('the state is ', state)
    print('the action is', action])
    
    possActions = ['a','b']
    currentReward = env[pos]
    possSuccStatesRewards = getAllSuccRewardForState(succStatesRewards, currentState)


    #bestSuccReward = 0
    #if possSuccStatesRewards[0] > possSuccStatesRewards[1]:
    #    bestSuccReward = possSuccStatesRewards[0]
    #else:
    #    bestSuccReward = possSuccStatesRewards[1]      
   

    bestValue = 0;
    for i in range(0,len(possActions)):
        print('the action ')
        if initalEnviroment:
            #this is the way to count the value for the initial enviroment
            newValue = probMove*(possSuccStatesRewards[i]) + probStay*(currentReward)
        else:
            #the optional policy V_k[s] = max_a Σ_s' p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′])
            newValue = probMove*(currentReward + gamma*possSuccStatesRewards[i]) + probStay*(currentReward + gamma*currentReward)
        print('one value is : ',newValue)
        #the converging optimal value function π(s)=argmax_a ∑_s′ p(s′|s,a)*(r(a,s,s′) + γ*V_k−1[s′]))
        #initialize for first loop or, if the newValues is better (within a epsilon range)
        if (i == 0) or ((newValue > bestValue)): # and ((newValue - bestValue) < eps)):
            bestValue = newValue   
        
    return bestValue
       
def getOptimalValue111(env,succStatesRewards,pos,probMove,probStay,gamma,eps,initalEnviroment):
    #save the inital enviroment and all updated enviroments for return later
    listOfEnviroments = [env]
    possibleActions = ['a','b']
    
    oldEnviroment = listOfEnviroments[i]
    newEnviroment = np.zeros(env.shape)
    for state in range(0,5):
        for a in range(0,2):
            action = possibleActions[a]
            succReward = getSuccRewardFromAction(succStatesRewards, state, action)
            bestSuccReward = getOptimalValue11(succStatesRewards,state)
            currentReward = oldEnviroment[state,a]
            # Q-learning formula
            newValue = currentReward + (learning_rate*(succReward + (gamma*bestSuccReward) - currentReward))
            #update with new reward
            newEnviroment[state,a] = newValue
    #save a new updated enviroment into an array to save the history
    listOfEnviroments.append(newEnviroment)     
    return listOfEnviroments


def updateEnviroment(env,succStatesRewards,probMove,probStay,gamma,eps,n_wanted_updates,initalEnvIncluded):

    #save the inital enviroment and all updated enviroments for return later
    listOfEnviroments = [env]

    # one loop will create a new enviroment with values from the first
    for i in range (0,n_wanted_updates): 
        
        oldEnv = listOfEnviroments[i]
        newEnviroment = np.zeros(env.shape)
        print('heeej',env.shape)
        for x in range(0,env.shape[0]):
            for y in range(0,env.shape[1]):
                pos = (x,y)
                if initalEnvIncluded & (i==0):
                    bValue = getOptimalValue(oldEnv,succStatesRewards,pos,probMove,probStay,gamma,eps,True)
                else:
                    bValue = getOptimalValue(oldEnv,succStatesRewards,pos,probMove,probStay,gamma,eps,False)
                #make a enviroment with the best values
                newEnviroment[pos] = bValue
            
        #save a new updated enviroment into an array to save the history
        listOfEnviroments.append(newEnviroment)
        
    return listOfEnviroments

n_wanted_updates = 1
env, succStatesRewards = createEnviroment()
enviroments = updateEnviroment(env,succStatesRewards,0.8,0.2,0.9,0.5,n_wanted_updates,True)

for i in range(0,len(enviroments)):
    print(enviroments[i])



heeej (5, 2)
the state is  0
the action is a
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  0
the action is b
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  1
the action is a
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  1
the action is b
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  2
the action is a
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  2
the action is b
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  3
the action is a
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  3
the action is b
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  4
the action is a
the action 
one value is :  0.0
the action 
one value is :  1.6
the state is  4
the action is b
the action 
one value is :  0.0
the action 
one value is :  1.6
[[0. 0.]
 [0. 0.]
 [0. 0.]


In [ ]:
print(env.compute_reward(achieved_goal=True))

TypeError: compute_reward() missing 2 required positional arguments: 'desired_goal' and 'info'

**4b) What is the importance of exploration in RL? Explain with an example.**

Exploration is important to not focus on specific areas of the data, and where we could otherwise end up with local optimums that are according to the
algorithm great but may not apply to other parts of the data. If we take a real life example when choosing cereal, where you have chosen cereal a multiple times
and know that you like them. You would continue to chose this cereal, **exploiting** the fact that you know that they're tasty. But you haven't explored
any other options, and maybe cereal B would be tastier, healthier, or cheaper? In order for you to find out, you have to **explore** new options. You want
what is best for you in the long run, not just in the moment, and it's the same for the algorithm. We can take new actions that can lead to a better overall 
outcome.

## Question 5

**5a) Give a summary of how a decision tree works and how it extends to random forests.**

A decision tree is a class of regression and classification methods that can be represented with a tree structured graph where nodes represent
questions, branches represent answers, and leaves represent labels. The first question is asked at the root of the tree, and for each level a new 
question is asked. Everytime a question is asked, a new branch is added and a new area in the feature space is split off. We do this until a
set number of splits has been achieved, and where we don't want to split if it doens't improve the impurity (homogenous).

Random Forests are a combination of decision trees but with more flexibility. So it's based on a decision tree, but the big difference is that a single
decision tree does not determine the answer but rather the whole forest. Then the majority of the vote determine the answer, and generally we then
minimize the variance of predictions since each decision tree are better or worse at specific elements of decisions. So we ask multiple decision trees
the same question and then take the majority as the answer.

**5b) Explain what makes reinforcement learning different from supervised learning tasks such as regression or classification.**

In RL the agent doens't usually know the environment, but can interact with it to learn and improve from it. Compared to regression or classification
where we need to have a previous understanding of the environment in order to get the optimal performance. By instead using RL we can figure out the
best results by trial and error. RL is also more independent than supervised learning methods (as the name suggests) where less tweaking by the user
needs to be done since the algorithm can learn from misstakes by themselves. Supervised learning also doesn't include exploration, since it's given
the dataset and the algorithm doesn't need to collect the data. It also typically only makes one decision, "is this image a chihuahua or muffin?", and
it will only learn if those decisions were right later.


# References
Primer/text based on the following references:
* http://www.cse.chalmers.se/~chrdimi/downloads/book.pdf
* https://github.com/olethrosdc/ml-society-science/blob/master/notes.pdf